// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB-Top1D51mIHVaAwWwwm_dOC0cythuD4',
    appId: '1:398662889533:web:6a32aa19e26bf929987a54',
    messagingSenderId: '398662889533',
    projectId: 'collectibles-memorabilia-app',
    authDomain: 'collectibles-memorabilia-app.firebaseapp.com',
    storageBucket: 'collectibles-memorabilia-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiuPJT3_8kVIOLco3vQRrkEtusP3C16jM',
    appId: '1:398662889533:android:7fb8cc7e47018e39987a54',
    messagingSenderId: '398662889533',
    projectId: 'collectibles-memorabilia-app',
    storageBucket: 'collectibles-memorabilia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASKwuITdveyPkbMof0VEXNhl_4ODAD1G8',
    appId: '1:398662889533:ios:686eb2cde1dab066987a54',
    messagingSenderId: '398662889533',
    projectId: 'collectibles-memorabilia-app',
    storageBucket: 'collectibles-memorabilia-app.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASKwuITdveyPkbMof0VEXNhl_4ODAD1G8',
    appId: '1:398662889533:ios:686eb2cde1dab066987a54',
    messagingSenderId: '398662889533',
    projectId: 'collectibles-memorabilia-app',
    storageBucket: 'collectibles-memorabilia-app.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB-Top1D51mIHVaAwWwwm_dOC0cythuD4',
    appId: '1:398662889533:web:78c2b607479bf3a2987a54',
    messagingSenderId: '398662889533',
    projectId: 'collectibles-memorabilia-app',
    authDomain: 'collectibles-memorabilia-app.firebaseapp.com',
    storageBucket: 'collectibles-memorabilia-app.firebasestorage.app',
  );

}